/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f2f2d9",
        "tertiary-fixed": "#ffdbc9",
        "background": "#fbfbe2",
        "tertiary-fixed-dim": "#ffb68c",
        "secondary": "#735c00",
        "primary-fixed": "#ffdad3",
        "on-tertiary": "#ffffff",
        "surface": "#fbfbe2",
        "on-secondary-fixed-variant": "#574500",
        "on-tertiary-fixed-variant": "#753401",
        "on-surface-variant": "#56423e",
        "surface-container-low": "#f5f5dc",
        "on-primary": "#ffffff",
        "secondary-fixed": "#ffe088",
        "on-background": "#1b1d0e",
        "on-primary-container": "#5a0d02",
        "on-primary-fixed": "#3e0500",
        "outline": "#89726d",
        "surface-bright": "#fbfbe2",
        "primary": "#9f402d",
        "surface-variant": "#e4e4cc",
        "on-tertiary-container": "#4b1e00",
        "tertiary-container": "#d27d47",
        "inverse-primary": "#ffb4a5",
        "on-tertiary-fixed": "#321200",
        "surface-tint": "#9f402d",
        "on-secondary-container": "#745c00",
        "outline-variant": "#ddc0ba",
        "tertiary": "#934b19",
        "on-error": "#ffffff",
        "surface-container-high": "#eaead1",
        "surface-container-highest": "#e4e4cc",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ffb4a5",
        "on-secondary-fixed": "#241a00",
        "on-primary-fixed-variant": "#802918",
        "inverse-surface": "#303221",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed65b",
        "surface-dim": "#dbdcc3",
        "on-surface": "#1b1d0e",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#e9c349",
        "primary-container": "#e2725b",
        "surface-container": "#efefd7"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
